# Generated by Django 4.2.28 on 2026-02-12 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verifylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='voicetemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='verifylog',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verifylog',
            name='threshold',
            field=models.FloatField(default=0.75),
        ),
        migrations.AddField(
            model_name='voicetemplate',
            name='embedding_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='voicetemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='voicetemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EnrollLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=128)),
                ('wav_count', models.IntegerField(default=0)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_msg', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enroll_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
