# Generated by Django 4.2.28 on 2026-02-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_verifylog_options_alter_voicetemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifylog',
            name='door_state',
            field=models.CharField(default='CLOSED', max_length=16),
        ),
    ]
