# Generated by Django 4.2.28 on 2026-02-13 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_add_verifylog_door_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifylog',
            name='error_msg',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='verifylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verify_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
