# Generated by Django 4.2.28 on 2026-02-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_admin_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifylog',
            name='intent',
            field=models.CharField(default='verify_only', max_length=64),
        ),
        migrations.AddField(
            model_name='verifylog',
            name='latency_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verifylog',
            name='response_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='verifylog',
            name='source',
            field=models.CharField(default='legacy', max_length=32),
        ),
    ]
