# configs/data.yaml
# Data Processing Configuration
# Usage: python -m scripts.data.feature_extraction --config configs/data.yaml

dataset:
  in_root: "data/processed"
  out_root: "data/features"
  feature_type: "mfcc_delta" # mfcc_delta, logmel
  n_mels: 40
  workers: 0 # 0 for auto-detect (max cpu - 1), 1 for single thread
