from django.urls import path
from .views import (
    RegisterView,
    LoginView,
    EnrollView,
    VerifyView,
    VerifyLogListView,
    VerifyLogBulkDeleteView,
    MyVerifyLogListView,
    EnrollLogListView,
    UserListView,
    UserDetailView,
    UserResetPasswordView,
    UserVoiceprintResetView,
    AdminSecretStatusView,
    AdminSecretSetView,
    AdminListView,
    AdminStaffListView,
    AdminStaffDetailView,
    AdminStaffBulkStatusView,
    AdminStaffBulkResetPasswordView,
    AdminAccessLogListView,
    ModelListView,
    ModelSwitchView,
    StatsView,
    DashboardView,
    CurrentUserView,
    VoiceprintStatusView,
    RocView,
    RocEvaluateView,
    ThresholdConfigView,
)

urlpatterns = [
    # 用户
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('me/', CurrentUserView.as_view(), name='current-user'),

    # 核心功能
    path('enroll/', EnrollView.as_view(), name='enroll'),
    path('verify/', VerifyView.as_view(), name='verify'),

    # 管理员
    path('my-logs/', MyVerifyLogListView.as_view(), name='my-logs'),
    path('logs/', VerifyLogListView.as_view(), name='verify-logs'),
    path('logs/bulk-delete/', VerifyLogBulkDeleteView.as_view(), name='verify-logs-bulk-delete'),
    path('enroll-logs/', EnrollLogListView.as_view(), name='enroll-logs'),
    path('users/', UserListView.as_view(), name='user-list'),
    path('users/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('users/<int:pk>/reset-password/', UserResetPasswordView.as_view(), name='user-reset-password'),
    path('users/<int:pk>/voiceprint/', UserVoiceprintResetView.as_view(), name='user-voiceprint-reset'),
    path('admin-secret/', AdminSecretSetView.as_view(), name='admin-secret-set'),
    path('admin-secret/status/', AdminSecretStatusView.as_view(), name='admin-secret-status'),
    path('admin-list/', AdminListView.as_view(), name='admin-list'),
    path('admins/', AdminStaffListView.as_view(), name='admin-staff-list'),
    path('admins/<int:pk>/', AdminStaffDetailView.as_view(), name='admin-staff-detail'),
    path('admins/bulk-status/', AdminStaffBulkStatusView.as_view(), name='admin-staff-bulk-status'),
    path('admins/bulk-reset-password/', AdminStaffBulkResetPasswordView.as_view(), name='admin-staff-bulk-reset-password'),
    path('admin-access-logs/', AdminAccessLogListView.as_view(), name='admin-access-logs'),
    path('models/', ModelListView.as_view(), name='model-list'),
    path('models/switch/', ModelSwitchView.as_view(), name='model-switch'),
    path('stats/', StatsView.as_view(), name='stats'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('threshold/', ThresholdConfigView.as_view(), name='threshold-config'),
    path('voiceprint-status/', VoiceprintStatusView.as_view(), name='voiceprint-status'),
    path('roc/', RocView.as_view(), name='roc'),
    path('roc/evaluate/', RocEvaluateView.as_view(), name='roc-evaluate'),
]
